spring:
  datasource:
    url: jdbc:mysql://localhost:13306/ipangbodb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update